### ISSUE TITLE
calling on null error

### ISSUE THREAD

**Issue by steveDivan** [Wizpna/chatbot#1]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
[   +6 ms] E/flutter ( 8105): Receiver: null
[   +1 ms] E/flutter ( 8105): Tried calling: []("queryText")

**Comment by PT-1** [comment]
Yes, same issue, did you found any solution to it?

**Comment by steveDivan** [comment]
Yes the first thing to do is to check that the google auth file.json generated  for your project is the file used in google cloud plateform and that the key is active.also check that the G cloud plateform key is sync with dialogflow project.
I also noticed the error some times occured when there is no match between the user message and any intent
